/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DraftBottle;

import DraftBottle.commands.CommandBus;
import DraftBottle.configs.ConfigBus;
import DraftBottle.listeners.ListenerBus;
import org.bukkit.plugin.Plugin;
import org.bukkit.plugin.java.JavaPlugin;
import redempt.redlib.commandmanager.CommandParser;
import redempt.redlib.config.ConfigManager;

public class PlugGividado extends JavaPlugin {

    public ConfigManager cman;

    public Plugin plug = this;

    @Override
    public void onEnable() {

        cman = ConfigManager.create(this).target(ConfigBus.class).saveDefaults().load();
        new CommandParser(this.getResource("commands.rdcml")).parse().register("draftbottle", new CommandBus());
        new ListenerBus(this).register();

    }

}
